FROM ubuntu:24.04

RUN apt update && apt install -y \
    flatpak \
    flatpak-builder \
    git \
    ca-certificates \
    xvfb \
    && rm -rf /var/lib/apt/lists/*

RUN flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

RUN flatpak install -y flathub org.gnome.Platform//49 org.gnome.Sdk//49 org.freedesktop.Sdk.Extension.rust-stable//25.08 org.freedesktop.Sdk.Extension.node22//25.08

WORKDIR /app
